#!/bin/sh
HISTFILE="$HOME/.cache/zsh/history"
HISTSIZE=10000
SAVEHIST=10000

export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.local/share/bob/nvim-bin":$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export PATH=$HOME/.miniconda/bin:$PATH
export PATH=/usr/bin/python3:$PATH
export PATH=$HOME/.zsh/usr_scripts:$PATH

export MANPAGER='nvim +Man!'
export MANWIDTH=999
export GOPATH=$HOME/.local/share/go:$PATH
export NVM_DIR="$HOME/.nvm"
export VI_MODE_ESC_INSERT="jk"

# FZF
export FZF_DEFAULT_COMMAND='rg --hidden -l ""'

export FZF_DEFAULT_OPTS=" \
--color=bg+:#313244,bg:-1,spinner:#f5e0dc,hl:#f38ba8 \
--color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
--color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8 \
--cycle --no-scrollbar --border=rounded --layout=reverse  \
--inline-info --min-height=20 \
--preview 'bat --color=always {}' --preview-window '~3'"
# CTRL-/ to toggle small preview window to see the full command
# CTRL-Y to copy the command into clipboard using pbcopy
export FZF_CTRL_R_OPTS="
--preview 'bat {}' --preview-window up:3:hidden:wrap
--bind 'ctrl-/:toggle-preview'
--bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
--color header:italic
--header 'Press CTRL-Y to copy command into clipboard'"

export EDITOR= "nvim"
export TERMINAL="kitty"
export VISUAL="nvim"
export SUDOEDIT="nvim"
export PAGER= "bat"
export BROWSER="firefox"
