#!/bin/sh

# some useful options (man zshoptions)
setopt autocd extendedglob nomatch menucomplete
setopt interactive_comments
setopt appendhistory
stty stop undef		# Disable ctrl-s to freeze terminal.
zle_highlight=('paste:none')


# completions
autoload -Uz compinit
zstyle ':completion:*' menu select
zstyle ':completion::complete:lsof:*' menu yes select
zmodload zsh/complist
compinit

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
autoload -U select-word-style && select-word-style bash
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# Colors
autoload -Uz colors && colors
LS_COLORS=$LS_COLORS:'ow=1;34:' ; export LS_COLORS #disable folder highlight


# Normal files to source
plug "$HOME/.zsh/catppuccin_mocha-zsh-syntax-highlighting.zsh"
plug "$HOME/.zsh/zsh-exports"
plug "$HOME/.zsh/zsh-vim-mode"
plug "$HOME/.zsh/zsh-aliases"
plug "$HOME/.zsh/zsh-local"

# Plugins
plug "zap-zsh/zap-prompt"
plug "zsh-users/zsh-autosuggestions"
plug "zsh-users/zsh-syntax-highlighting"
plug "Aloxaf/fzf-tab"
plug "kjhaber/tm.zsh"
plug "kutsan/zsh-system-clipboard"
# For more plugins: https://github.com/unixorn/awesome-zsh-plugins
# More completions https://github.com/zsh-users/zsh-completions

# Key-bindings
bindkey '^[[P' delete-char
bindkey '^H' backward-kill-word
bindkey "^p" up-line-or-beginning-search # Up
bindkey "^n" down-line-or-beginning-search # Down
bindkey -M menuselect '^[[Z' reverse-menu-complete # shift-tab to go to previous choice

# FZF
export FZF_DEFAULT_COMMAND='rg --hidden -l ""'

export FZF_DEFAULT_OPTS=" \
--color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
--color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
--color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8  \
--cycle --no-scrollbar --border=rounded --layout=reverse  \
--inline-info --min-height=20"
# CTRL-/ to toggle small preview window to see the full command
# CTRL-Y to copy the command into clipboard using pbcopy
export FZF_CTRL_R_OPTS="
--preview 'bat {}' --preview-window up:3:hidden:wrap
--bind 'ctrl-/:toggle-preview'
--bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
--color header:italic
--header 'Press CTRL-Y to copy command into clipboard'"
# Edit line in vim with ctrl-e:
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

#Custom
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' #Auto completion case insensitve
unsetopt BEEP # beeping is annoying

eval "$(zoxide init zsh)"
