#!/bin/sh

# some useful options (man zshoptions)
setopt autocd extendedglob nomatch menucomplete
setopt interactive_comments
setopt appendhistory
stty stop undef		# Disable ctrl-s to freeze terminal.
zle_highlight=('paste:none')


# completions
autoload -Uz compinit
zstyle ':completion:*' menu select
zstyle ':completion::complete:lsof:*' menu yes select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 
zmodload zsh/complist
compinit

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
autoload -U select-word-style && select-word-style bash
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# Colors
autoload -Uz colors && colors
LS_COLORS=$LS_COLORS:'ow=1;34:' ; export LS_COLORS #disable folder highlight


# Normal files to source
plug "$HOME/.zsh/catppuccin_mocha-zsh-syntax-highlighting.zsh"
plug "$HOME/.zsh/zsh-exports"
plug "$HOME/.zsh/zsh-aliases"
plug "$HOME/.zsh/zsh-local"

# completions
plug "esc/conda-zsh-completion"

# Plugins
plug "zap-zsh/zap-prompt"
plug "zap-zsh/vim"
plug "zsh-users/zsh-autosuggestions"
plug "zsh-users/zsh-syntax-highlighting"
plug "Aloxaf/fzf-tab"
plug "kjhaber/tm.zsh" "d15087a2375d1bee4af1b0bebbb1348577190f03"
plug "kutsan/zsh-system-clipboard"
# For more plugins: https://github.com/unixorn/awesome-zsh-plugins
# More completions https://github.com/zsh-users/zsh-completions

# Key-bindings
bindkey '^[[P' delete-char
bindkey '^H' backward-kill-word
bindkey "^p" up-line-or-beginning-search # Up
bindkey "^n" down-line-or-beginning-search # Down
bindkey -M menuselect '^[[Z' reverse-menu-complete # shift-tab to go to previous choice
bindkey '^f' autosuggest-execute

# Edit line in vim with ctrl-e:
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

#Custom
unsetopt BEEP # beeping is annoying

eval "$(zoxide init zsh)"
